{
  imports = [
    ./niri
    ./wm
    ./audacity.nix
    ./davinci-resolve.nix
    ./deltachat.nix
    ./firefox.nix
    ./element.nix
    ./feishin.nix
    ./fluxer.nix
    ./gimp.nix
    ./gtk.nix
    ./hyfetch.nix
    ./inkscape.nix
    ./krita.nix
    ./libreoffice.nix
    ./obsidian.nix
    ./plasma.nix
    ./prismlauncher.nix
    ./qbittorrent.nix
    ./r2modman.nix
    ./lmms.nix
    ./mpv.nix
    ./nemo.nix
    ./sddm.nix
    ./signal.nix
    ./steam.nix
    ./thunderbird.nix
    ./vlc.nix
  ];
}
