{
  imports = [
    ./audacity.nix
    ./firefox.nix
    ./feishin.nix
    ./gimp.nix
    ./keyd.nix
    ./libreoffice.nix
    ./lumafly.nix
    ./mullvad.nix
    ./niri.nix
    ./obsidian.nix
    ./osu.nix
    ./patchance.nix
    ./plasma.nix
    ./prismlauncher.nix
    ./qbittorrent.nix
    ./r2modman.nix
    ./sddm.nix
    ./signal.nix
    ./steam.nix
    ./thunderbird.nix
    ./vlc.nix
    ./vms.nix
  ];
}
